const { chromium } = require('playwright');
(async ()=>{
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage();
  await page.goto('https://conduit.bondaracademy.com/login');
  await page.fill('[placeholder="Email"]', 'vananh217.tm@gmail.com');
  await page.fill('[placeholder="Password"]', '12345678');
  await Promise.all([page.waitForURL('**/'), page.click('button:has-text("Sign in")')]);
  await page.waitForTimeout(1000);
  console.log('logged in url', page.url());
  console.log('new article button count', await page.locator('text=New Article').count());
  await page.click('text=New Article');
  await page.waitForURL('**/editor');
  console.log('editor url', page.url());
  console.log('article title placeholder count', await page.locator('[placeholder="Article Title"]').count());
  console.log('description placeholder count', await page.locator('[placeholder="What\'s this article about?"]').count());
  console.log('body placeholder count', await page.locator('[placeholder="Write your article (in markdown)"]').count());
  console.log('publish buttons', await page.locator('button:has-text("Publish Article")').count());
  await page.fill('[placeholder="Article Title"]', 'Playwright Test AnhNTV');
  await page.fill('[placeholder="What\'s this article about?"]', 'Demo desscription');
  await page.fill('[placeholder="Write your article (in markdown)"]', 'Demo body content');
  await Promise.all([page.waitForNavigation({ url: '**/article/**' }), page.click('button:has-text("Publish Article")')]);
  await page.waitForTimeout(1000);
  console.log('after publish url', page.url());
  console.log('heading count', await page.locator('h1').count());
  console.log('heading text', await page.locator('h1').innerText());
  await page.screenshot({ path: 'create-article-result.png', fullPage: true });
  await browser.close();
})();
